# Generated by Django 5.2.17 on 2026-08-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('merchant', 'Merchant'), ('customer', 'Customer')], max_length=20)),
                ('recipient_id', models.PositiveBigIntegerField()),
                ('type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store.storesettings')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id', 'is_read'], name='idx_notif_recipient_unread'), models.Index(fields=['store', 'created_at'], name='idx_notif_store_date')],
            },
        ),
    ]
