# Generated by Django 5.2.17 on 2026-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session cookie yang membuat order (ownership check)', max_length=64, null=True),
        ),
    ]
