# Generated by Django 5.2.17 on 2026-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token acak tak-tebakan (UUID) sbg kredensial akses order (anti-IDOR & anti-session-fixation)', max_length=64, null=True),
        ),
    ]
