# Generated by Django 5.2.17 on 2026-08-26 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='Nama Toko')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='store/logos/')),
                ('favicon_url', models.ImageField(blank=True, null=True, upload_to='store/favicons/')),
                ('description', models.TextField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('shipping_policy', models.TextField(blank=True, null=True)),
                ('shipping_method', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_kota', 'Per Kota'), ('gratis_ons', 'Gratis Ongkir Minimum')], default='flat_rate', max_length=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_shipping_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_settings',
            },
        ),
    ]
